### ISSUE TITLE
Something wrong with rotation handles

### ISSUE THREAD

**Issue by trsh** [pshtif/RuntimeTransformHandle#2]
When rotating Y (green) it goes into opposite direction then the mouse. Something similar with X. I tried to play with `_xmod` & `_ymod`, but could not get it working right. I fix one, another is broke, and in general I'm shooting the dark, because I don't understand the logic there :D

**Comment by pshtif** [comment]
Hi the gizmo handling/calculations was changed to Blender like style I hope it is more logical now.
