### ISSUE TITLE
Couldn't find RuntimeTransformHanlde in Package Manager

### ISSUE THREAD

**Issue by duongtran11** [pshtif/RuntimeTransformHandle#5]
![2022-06-26_112609](https://user-images.githubusercontent.com/67900559/175799389-4b107c18-ad70-4e87-954a-671510642625.png)

After Scoped Registry added to the Package Manager I still can't find RuntimeTranformHandle in Package Manager

**Comment by pshtif** [comment]
Yep, sorry this package was missing in the new repo, I added it again.
